# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: "Getting started"
  link: "/getting-started"
- label: Usage
  items:
    - label: "Defining policies"
      link: "/usage/policies"
    - label: "Workflow as OPA REST APIs"
      link: "/usage/opa_rest"
- label: ""
- label: ""
- label: Github
  link: "https://github.com/cyralinc/brewOPA"
